language: python
python:
  - "2.7"
  - "3.6"

# Command to install dependencies
install:
  - ./.travis-install-dependencies.sh

# Command to run tests
script:
  - regtests/runtests.sh

# Run the coverage analysis after tests
after_success:
    coveralls;

# safelist
branches:
  only:
  - master
