language: python

python:
  - "2.7"
  - "3.6"
os:
  - linux
  - osx

# Command to install dependencies
install:
  - ./.travis-install-dependencies.sh

# Command to run tests
script:
  - regtests/runtests.sh

# Defines the branches on which the tests are run on
branches:
  only:
  - master

# Defines build stages.
jobs:
  include:
      # Sends the coverage report to coveralls.io. Only sent from python 3.
    - stage: coverage
      python: 3.6
      os: linux
      script: coveralls
